import Head from "next/head";
import AppRight from "../components/AppRight";

export default function Home() {
  return (
    <div className="flex">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          background:
            "url(https://res.cloudinary.com/dssvrf9oz/image/upload/v1622735422/mads-schmidt-rasmussen-xfngap_DToE-unsplash_k3yczw.jpg)",
          flex: "0.6",
        }}
        className="font-poppins flex flex-col h-screen justify-center items-center !bg-cover !bg-bottom object-contain rounded-r-3xl "
      >
        <h2 className="absolute top-10 left-10 text-2xl font-bold text-white">
          TooTravel
        </h2>
        <div className="flex flex-col w-3/5">
          <h1 className="text-5xl font-semibold text-white">
            The most beautiful places in the world!
          </h1>
          <p className="text-white text-sm mt-10">
            Plan your vacation on the most beautiful places in the world
          </p>
          <button className="bg-orange w-60 text-[#fff] py-2 h-10 mt-10 px-5 rounded-xl">
            Get started
          </button>
        </div>
        <div className="absolute bottom-10 left-20 flex items-center">
          <p className="text-white">01</p>
          <div className="h-[2px] w-8 bg-white mr-2"></div>
          <div className="h-[2px] w-8 bg-white mr-2 bg-opacity-20 hover:bg-opacity-100 cursor-pointer"></div>
          <div className="h-[2px] w-8 bg-white mr-2 bg-opacity-20 hover:bg-opacity-100 cursor-pointer"></div>
          <p className="text-white">03</p>
        </div>
      </div>
      <div style={{ flex: "0.4" }}>
        <AppRight />
      </div>
    </div>
  );
}
